SELECT MCDP_CD AS 진료과코드, COUNT(PT_NO) AS 5월예약건수
FROM APPOINTMENT
# WHERE DATE_FORMAT(DATE(APNT_CNCL_YMD),'%Y-%m') = '2022-05'
WHERE DATE_FORMAT(DATE(APNT_YMD),'%Y-%m') = '2022-05'
GROUP BY 진료과코드
ORDER BY 5월예약건수 ASC,
진료과코드 ASC;